# Generated by Django 4.1.1 on 2024-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_profile_preferred_apartment_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preference_neat",
            field=models.CharField(
                choices=[
                    ("No Preference", "No Preference"),
                    ("Neat", "Neat"),
                    ("Messy", "Messy"),
                ],
                default="No Preference",
                max_length=128,
            ),
        ),
    ]
